config/routes.rb
Rails.application.routes.draw do
  get 'page' => 'page#index'

  resources :countries
  resources :calender_dates
  resources :holidays

  root 'page#index'

end

app/models/holiday.rb
class Holiday < ActiveRecord::Base
	include HTTParty
	
	has_many :holiday_date
	has_many :calender_date, through: :holiday_date

	def self.get_holidays_json
		h = JSON.parse(HTTParty.get('http://holidayapi.com/v1/holidays?country=US&year=2015').body)["holidays"]

		h.each do |date, info|
			Holiday.where(name: info["name"]).first_or_create
		end

	end
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  before_action :set_holiday, only: [:show, :edit, :update, :destroy]

  # GET /holidays
  # GET /holidays.json
  def index
    @holidays = Holiday.all
    @calender_dates = CalenderDate.all
    @countries = Country.all   

    if params[:set_country] && params[:set_year]
      ct = params[:set_country]
      yr = params[:set_year]
      dt = DateTime.new(yr.to_i)
      boy = dt.beginning_of_year.to_date
      eoy = dt.end_of_year.to_date
      calender = CalenderDate.where("calender_date >= ? and calender_date <= ?", boy, eoy).all
      @holiday_date = HolidayDate.where("country_id = ? and calender_date_id >= ? and calender_date_id <= ?", ct.to_i, calender.first.id, calender.last.id)
    else
      #@holiday_date = HolidayDate.find_by_sql("select * " +
      #                                        "FROM holiday_dates h " + 
      #                                        "LEFT JOIN calender_dates c " +
      #                                        "ON h.country_id = 2 " +
      #                                        "and extract(year from c.calender_date) = 2015 " +
      #                                        "and c.id = h.calender_date_id")
      dt = DateTime.new(2015)
      boy = dt.beginning_of_year.to_date
      eoy = dt.end_of_year.to_date
      calender = CalenderDate.where("calender_date >= ? and calender_date <= ?", boy, eoy).all
      @holiday_date = HolidayDate.where("country_id = 2 and calender_date_id >= ? and calender_date_id <= ?", calender.first.id, calender.last.id)
        
    end
  end

  # GET /holidays/1
  # GET /holidays/1.json
  def show
  end

  # GET /holidays/new
  def new
    @holiday = Holiday.new
    
  end

  # GET /holidays/1/edit
  def edit
  end

  # POST /holidays
  # POST /holidays.json
  def create
    @holiday = Holiday.new(holiday_params)

    respond_to do |format|
      if @holiday.save
        format.html { redirect_to @holiday, notice: 'Holiday was successfully created.' }
        format.json { render :show, status: :created, location: @holiday }
      else
        format.html { render :new }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /holidays/1
  # PATCH/PUT /holidays/1.json
  def update
    respond_to do |format|
      if @holiday.update(holiday_params)
        format.html { redirect_to @holiday, notice: 'Holiday was successfully updated.' }
        format.json { render :show, status: :ok, location: @holiday }
      else
        format.html { render :edit }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holidays/1
  # DELETE /holidays/1.json
  def destroy
    @holiday.destroy
    respond_to do |format|
      format.html { redirect_to holidays_url, notice: 'Holiday was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_holiday
      @holiday = Holiday.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def holiday_params
      params[:holiday]
    end
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/views/holidays/_form.html.erb
<%= form_for(@holiday) do |f| %>
  <% if @holiday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@holiday.errors.count, "error") %> prohibited this holiday from being saved:</h2>

      <ul>
      <% @holiday.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/holidays/edit.html.erb
<h1>Editing Holiday</h1>

<%= render 'form' %>

<%= link_to 'Show', @holiday %> |
<%= link_to 'Back', holidays_path %>

app/views/holidays/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Holidays for <%= @countries.find(@holiday_date.first.country_id).country %> 
  in <%= @calender_dates.find(@holiday_date.first.calender_date_id).calender_date.year %></h1>

<%= form_tag holidays_path, :method => :get, class: 'get_country'  do %>
  <%= select_tag "set_country", options_from_collection_for_select(@countries, 'id', 'country', selected: params[:set_country])%>
  <%= select_tag "set_year", options_for_select((Date.today.year .. (Date.today.year+30)), selected: params[:set_year]) %>
  <%= submit_tag 'submit' %>

<% end %>

<table class = "table table-striped"> 
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @holiday_date.each do |holiday_date| %>
      <tr>
        <td><%= @holidays.find(holiday_date.holiday_id).name%></td>
        <td>Date: <%= @calender_dates.find(holiday_date.calender_date_id).calender_date %></td>
        <td>Country: <%= @countries.find(holiday_date.country_id).country %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/holidays/new.html.erb
<h1>New Holiday</h1>

<%= render 'form' %>

<%= link_to 'Back', holidays_path %>

app/views/holidays/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_holiday_path(@holiday) %> |
<%= link_to 'Back', holidays_path %>