config/routes.rb
Rails.application.routes.draw do
  get 'page' => 'page#index'

  resources :countries
  resources :calender_dates
  resources :holidays

  root 'page#index'

end

app/models/calender_date.rb
class CalenderDate < ActiveRecord::Base
	has_many :hoilday_date
	has_many :holidays, through: :holiday_date
	
end

app/controllers/calender_dates_controller.rb
class CalenderDatesController < ApplicationController
  before_action :set_calender_date, only: [:show, :edit, :update, :destroy]

  # GET /calender_dates
  # GET /calender_dates.json
  def index
    @calender_dates = CalenderDate.all
  end

  # GET /calender_dates/1
  # GET /calender_dates/1.json
  def show
  end

  # GET /calender_dates/new
  def new
    @calender_date = CalenderDate.new
  end

  # GET /calender_dates/1/edit
  def edit
  end

  # POST /calender_dates
  # POST /calender_dates.json
  def create
    @calender_date = CalenderDate.new(calender_date_params)

    respond_to do |format|
      if @calender_date.save
        format.html { redirect_to @calender_date, notice: 'Calender date was successfully created.' }
        format.json { render :show, status: :created, location: @calender_date }
      else
        format.html { render :new }
        format.json { render json: @calender_date.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calender_dates/1
  # PATCH/PUT /calender_dates/1.json
  def update
    respond_to do |format|
      if @calender_date.update(calender_date_params)
        format.html { redirect_to @calender_date, notice: 'Calender date was successfully updated.' }
        format.json { render :show, status: :ok, location: @calender_date }
      else
        format.html { render :edit }
        format.json { render json: @calender_date.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calender_dates/1
  # DELETE /calender_dates/1.json
  def destroy
    @calender_date.destroy
    respond_to do |format|
      format.html { redirect_to calender_dates_url, notice: 'Calender date was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calender_date
      @calender_date = CalenderDate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calender_date_params
      params[:calender_date]
    end
end

app/helpers/calender_dates_helper.rb
module CalenderDatesHelper
end

app/views/calender_dates/_form.html.erb
<%= form_for(@calender_date) do |f| %>
  <% if @calender_date.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@calender_date.errors.count, "error") %> prohibited this calender_date from being saved:</h2>

      <ul>
      <% @calender_date.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calender_dates/edit.html.erb
<h1>Editing Calender Date</h1>

<%= render 'form' %>

<%= link_to 'Show', @calender_date %> |
<%= link_to 'Back', calender_dates_path %>

app/views/calender_dates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Calender Dates</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @calender_dates.each do |calender_date| %>
      <tr>
        <td><%= link_to 'Show', calender_date %></td>
        <td><%= link_to 'Edit', edit_calender_date_path(calender_date) %></td>
        <td><%= link_to 'Destroy', calender_date, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Calender date', new_calender_date_path %>

app/views/calender_dates/new.html.erb
<h1>New Calender Date</h1>

<%= render 'form' %>

<%= link_to 'Back', calender_dates_path %>

app/views/calender_dates/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_calender_date_path(@calender_date) %> |
<%= link_to 'Back', calender_dates_path %>